name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      with:
        gradle-version: 8.7

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Run Tests
      run: ./gradlew test

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/jacocoHtml/

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5
    
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
            branch_regex_release='^release/[0-9]+\.[0-9]+\.[0-9]+$'
            branch_regex_feature='^feature/.+$'
            if [[ ! ${{ github.head_ref }} =~ $branch_regex_release ]] && [[ ${{ github.base_ref }} == "main" ]]; then
                echo "Merge requests to main branch are only allowed from release/* branches with semantic versioning."
                exit 1
            elif [[ ! ${{ github.head_ref }} =~ $branch_regex_feature ]] && [[ ${{ github.base_ref }} == "develop" ]]; then
                echo "Merge requests to develop branch are only allowed from feature/* branches."
                exit 1
            fi